apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.argocd.appname }}-vswh"
  namespace: {{ .Values.argocd.namespace }}
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: {{ .Values.project }}
  destination:
    server: {{ .Values.cluster.address }}
    namespace: "{{ .Values.cluster.namespace }}-vswh"
  sources:
  - repoURL: {{ .Values.values.repo_URL }}
    targetRevision: {{ .Values.values.branch }}
    ref: values
  - repoURL: {{ .Values.vault_webhook.repo_URL }}
    targetRevision: {{ .Values.vault_webhook.targetRevision }}
    chart: {{ .Values.vault_webhook.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.vault_webhook.valueFiles }}
        - $values/app-values/vault-webhook/{{ . }}
        {{- end }}
      values: |
        watchNamespace: {{ .Values.cluster.namespace }}
        fullnameOverride: vault-webhook-{{ .Release.Namespace }}
        serviceAccount:
          name: vault-webhook-service-account
        {{- if .Values.vault_webhook.resources }}
        resources: {{- toYaml .Values.vault_webhook.resources | nindent 10 }}
        {{- end }}