argocd:
  appname: common
  namespace: argocd

project: default

agentList:
  authorities:
    - authority1
  consumers:
    - consumer01
  providers:
    - dataprovider01

cluster:
  address: https://kubernetes.default.svc
  namespace: common
  issuer: dev-prod
  kubeStateHost: kube-prometheus-stack-kube-state-metrics.devsecopstools.svc.cluster.local:8080

namespaceTag: common
domainSuffix: int.simpl-europe.eu

hashicorp:
  secretEngine: dev-int
  role: dev-int-role

values:
  repo_URL: https://code.europa.eu/simpl/simpl-open/development/agents/common_components.git
  branch: v2.0.0

monitoring:
  enabled: true
  operator:
    repo_URL: https://helm.elastic.co/
    chart_name: eck-operator
    crds_chart_name: eck-operator-crds
    targetRevision: "2.16.1"
    nameOverride: eck-operator
    valueFiles:
      - values.yaml
  projectID: "828"
  targetRevision: 0.1.14
  chart_name: eck-monitoring
  fullnameOverride: elastic
  params:
    diskSpace: 
      elasticsearch: 50Gi
      logstash: 3Gi
    count:
      elasticsearch: 3
      kibana: 2
      logstash: 1

vault_operator:
  repo_URL: ghcr.io/bank-vaults/helm-charts
  targetRevision: 1.22.5
  chart_name: vault-operator
  resources:
    requests:
      cpu: "0"
      memory: "0"

vault_webhook:
  repo_URL: ghcr.io/bank-vaults/helm-charts
  targetRevision: 1.21.4
  chart_name: vault-secrets-webhook
  resources:
    requests:
      cpu: "0"
      memory: "0"

vault_injector:
  repo_URL: https://helm.releases.hashicorp.com
  targetRevision: 0.30.0
  chart_name: vault
  resources:
    requests:
      cpu: "0"
      memory: "0"

vault:
  projectID: "1080"
  targetRevision: 1.1.3
  chart_name: vault
  resources:
    requests:
      cpu: "0"
      memory: "0"

confluent_operator:
  repo_URL: https://packages.confluent.io/helm
  chart_name: confluent-for-kubernetes
  targetRevision: 0.1193.34
  nameOverride: confluent-operator

kafka:
  projectID: "976"
  targetRevision: 1.0.1
  chart_name: kafka
  auth: 
    enabled: true
  topic:
    autocreate: true
  valueFiles:
    - values.yaml

redpanda:
  repo_URL: https://charts.redpanda.com
  chart_name: console
  targetRevision: 0.7.31
  nameOverride: redpanda
  valueFiles:
    - values.yaml

pg_operator:
  repo_URL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  chart_name: postgres-operator
  targetRevision: 1.14.0
  nameOverride: pg-operator
  valueFiles:
    - values.yaml

pg_admin:
  repo_URL: https://helm.runix.net
  chart_name: pgadmin4
  targetRevision: 1.44.0
  nameOverride: pg-admin
  valueFiles:
    - values.yaml

pg_cluster:
  projectID: "1024"
  targetRevision: 1.0.0
  chart_name: pg-cluster
  valueFiles:
    - values.yaml

redis:
  repo_URL: 'https://charts.bitnami.com/bitnami'
  targetRevision: 19.6.0
  chart_name: redis
  nameOverride: redis
  master:
    resourcesPreset: "none"
    resources:
      requests:
        cpu: "0"
        memory: "0"
  valueFiles:
    - values.yaml
    
redis_commander:
  repo_URL: 'https://github.com/joeferner/redis-commander.git'
  targetRevision: master
  nameOverride: redis-commander
  path: 'k8s/helm-chart/redis-commander'
  valueFiles:
    - values.yaml

notification:
  projectID: "1002"
  targetRevision: 0.0.3
  nameOverride: simpl-notification
  chart_name: simpl-notification-service
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

mailpit:
  enabled: true
  repo_URL: 'https://jouve.github.io/charts/'
  targetRevision: 0.23.1
  chart_name: mailpit
  nameOverride: mailpit
  valueFiles:
    - values.yaml